### ISSUE TITLE
It seems I have a short proof of P=NP - check it

### ISSUE THREAD

**Issue by vporton** [coq/stdlib2#24]
I've produced a short and much elementary proof of P=NP (without an efficient algorithm presented). I sent it to a reputable CS journal and insofar there were no errors noticed by the editor. (However, I myself found several errors, that are already corrected in the attached file.)

You should check my proof.

[p=np-merkle.pdf](https://github.com/leanprover/lean4-nightly/files/6725186/p.np-merkle.pdf)

**Comment by SkySkimmer** [comment]
This has nothing to do with coq or stdlib2

**Comment by vporton** [comment]
@SkySkimmer Got your position: stdlib2 should not contain a proof of P=NP.
